In [1]:
import pandas as pd
import numpy as np

In [23]:
df = pd.DataFrame({
    'id':[1,2,3,4,5],
    'name':['tom','jack','alice','luce','mike'],
    'age':[15,17,20,26,30],
    'score':[23,45,78,99,44]
},index=[1,2,3,4,5],columns=['name','id','age','score']  # columns调整列的顺序
)

In [3]:
# 1. index
print('行索引:',df.index)

行索引: Index([1, 2, 3, 4, 5], dtype='int64')

In [4]:
# 2. 列标签
print('列标签:',df.columns)

列标签: Index(['name', 'id', 'age'], dtype='object')

In [5]:
# 3. 值
print('值:',df.values)

值: [['tom' 1 15]
 ['jack' 2 17]
 ['alice' 3 20]
 ['luce' 4 26]
 ['mike' 5 30]]

In [6]:
# 4. ndim 维度
print('维度:',df.ndim)

维度: 2

In [7]:
# 4. dtypes 数据类型
print('数据类型:',df.dtypes)

数据类型: name    object
id       int64
age      int64
dtype: object

In [8]:
# 5. shape 形状
print('形状:',df.shape)

形状: (5, 3)

In [9]:
# 6. size 元素个数
print('元素个数:',df.size)

元素个数: 15

In [10]:
# 7. 行列转置
print(df.T)

        1     2      3     4     5
name  tom  jack  alice  luce  mike
id      1     2      3     4     5
age    15    17     20    26    30

In [24]:
print(df)

    name  id  age  score
1    tom   1   15     23
2   jack   2   17     45
3  alice   3   20     78
4   luce   4   26     99
5   mike   5   30     44

In [ ]:
# 8. 获取元素 loc iloc at iat
# 获取某行的数据
print(df.loc[4])
print(df.iloc[3])
# 获取某列数据
print(df.loc[:,'name'])
print(df.iloc[:,0])
print(df['name'])
print(df.name)
print(df[['name']])

name    luce
id         4
age       26
Name: 4, dtype: object
name    luce
id         4
age       26
Name: 4, dtype: object
1      tom
2     jack
3    alice
4     luce
5     mike
Name: name, dtype: object
1      tom
2     jack
3    alice
4     luce
5     mike
Name: name, dtype: object
1      tom
2     jack
3    alice
4     luce
5     mike
Name: name, dtype: object
1      tom
2     jack
3    alice
4     luce
5     mike
Name: name, dtype: object

In [18]:
# 获取单个数据
print(df.at[3,'name'])
print(df.iat[2,0])

alice
alice

In [21]:
# 查看部分数据
print(df.head())
print(df.tail(3))

    name  id  age
1    tom   1   15
2   jack   2   17
3  alice   3   20
4   luce   4   26
5   mike   5   30
    name  id  age
3  alice   3   20
4   luce   4   26
5   mike   5   30

In [27]:
# 使用布尔索引筛选数据
df[df.score>70]
df[ (df['score']>70) & (df.age<20)]

Empty DataFrame
Columns: [name, id, age, score]
Index: []

In [28]:
# 随机抽样
df.sample(3)

   name  id  age  score
5  mike   5   30     44
2  jack   2   17     45
4  luce   4   26     99