In [3]:
import pandas as pd
data = pd.DataFrame({
    'name':['alice','alice','bob','alice','jack','bob'],
    'age':[26,25,30,25,35,30],
    'city':['NY','NY','LA','NY','SF','LA']
})
data

    name  age city
0  alice   26   NY
1  alice   25   NY
2    bob   30   LA
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

In [7]:
data.duplicated()  # 一整条记录都是一样的，标记为重复，返回True
data.drop_duplicates()  # 去重
data.drop_duplicates(subset=['name'])  # 指定某一列重复的去重,留下最前面的
data.drop_duplicates(subset=['name'],keep='last') # 指定某一列重复的去重,留下最后面的

    name  age city
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

In [13]:
# 数据类型的转换
df = pd.read_csv('data/sleep.csv')
df.dtypes

person_id                    int64
gender                      object
age                          int64
occupation                  object
sleep_duration             float64
sleep_quality              float64
physical_activity_level      int64
stress_level                 int64
bmi_category                object
blood_pressure              object
heart_rate                   int64
daily_steps                  int64
sleep_disorder              object
dtype: object

In [17]:
# 数值类型转换
df['age'] = df['age'].astype('int16')
# 转成类别类型
df['gender'] = df['gender'].astype('category')
df.dtypes
# 将类别改为布尔
df['is_male'] = df['gender'].map({'Female':True,'Male':False})